---
language: python
python: "2.7"

sudo: required
dist: trusty
services:
  - docker

env:
  - distribution: centos
    version: 7
  - distribution: centos
    version: 6
  - distribution: ubuntu
    version: 16.04
  - distribution: ubuntu
    version: 14.04

before_install:
  - 'sudo docker run -it --name=test_dummy --privileged --detach --volume="${PWD}":/etc/ansible/roles/hotspot-ansible:rw cyverse/ansible-test:latest-${distribution}-${version} bash'

script:
  # Syntax check
  - sudo docker exec test_dummy ansible-playbook /etc/ansible/roles/hotspot-ansible/tests/test.yml -i tests/inventory --syntax-check
  # Run
  - sudo docker exec test_dummy ansible-playbook /etc/ansible/roles/hotspot-ansible/tests/test.yml -i tests/inventory
